#! /bin/bash
wget http://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-2.7.2.tgz
tar -zxvf mongodb-linux-x86_64-ubuntu1404-2.7.2.tgz
export PATH=/home/$USER/CS244proj3/mongodb-linux-x86_64-ubuntu1404-2.7.2/bin:$PATH
sudo mkdir -p /data/db
sudo mkdir -p /var/log/mongodb
sudo mkdir -p /var/lib/mongodb

sudo chown -R $USER /data/db
sudo chown -R $USER /var/log/mongodb
sudo chown -R $USER /var/lib/mongodb

echo export PATH=/home/$USER/CS244proj3/mongodb-linux-x86_64-ubuntu1404-2.7.2/bin:$PATH >> ~/.profile 
